config/routes.rb
require 'sidekiq/web'

Neighborly::Application.routes.draw do

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)

  devise_for :users, path: '',
    path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
    controllers:  { omniauth_callbacks: :omniauth_callbacks }


  devise_scope :user do
    post '/sign_up', to: 'devise/registrations#create', as: :sign_up
  end

  get '/thank_you' => "static#thank_you"

  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }

  # Mountable engines
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount Neighborly::Balanced::Creditcard::Engine => '/balanced/creditcard/', as: :neighborly_balanced_creditcard
  mount Neighborly::Balanced::Bankaccount::Engine => '/balanced/bankaccount/', as: :neighborly_balanced_bankaccount
  mount Neighborly::Balanced::Engine => '/balanced/', as: :neighborly_balanced

  # Non production routes
  if Rails.env.development?
    resources :emails, only: [ :index, :show ]
  end

  # Channels
  constraints subdomain: /^(?!www|secure|test|local|staging|neighborly|neighborly-staging)(\w+)/ do
    namespace :channels, path: '' do
      get '/', to: 'profiles#show', as: :profile
      resources :channels_subscribers, only: [:index, :create, :destroy]

      namespace :admin do

        get '/', to: 'dashboard#index', as: :dashboard

        namespace :reports do
          resources :subscriber_reports, only: [ :index ]
        end

        resources :followers, only: [ :index ]

        resources :projects, only: [ :index, :update] do
          member do
            put 'approve'
            put 'reject'
            put 'push_to_draft'
            put 'push_to_soon'
          end
        end
      end

      resource :profile, only: [:show]
      resources :projects, only: [:new, :create] do
        collection do
          get 'video'
        end
      end
      # NOTE We use index instead of create to subscribe comming back from auth via GET
      resource :channels_subscriber, only: [:show, :destroy], as: :subscriber
    end
  end

  mount Neighborly::Admin::Engine => '/admin/', as: :neighborly_admin

  # Root path should be after channel constraints
  root to: 'projects#index'

  # Static Pages
  get '/sitemap',               to: 'static#sitemap',             as: :sitemap
  get '/how-it-works',          to: 'static#how_it_works',        as: :how_it_works
  get '/fundraising',           to: 'static#fundraising',         as: :fundraising
  get '/crowdfunding',          to: 'static#crowdfunding',        as: :crowdfunding
  get "/about",                 to: "static#about",               as: :about
  get "/faq",                   to: "static#faq",                 as: :faq
  get "/starting",              to: "static#starting",            as: :starting
  get "/idea_concept",          to: "static#idea_concept",        as: :idea_concept
  get "/terms",                 to: "static#terms",               as: :terms
  get "/privacy",               to: "static#privacy",             as: :privacy
  get "/start",                 to: "projects#start",             as: :start
  get "/kontakt",               to: "static#kontakt",             as: :kontakt
  get "/datenschutz",           to: "static#datenschutz",         as: :datenschutz
  get "/agb",                   to: "static#agb",                 as: :agb
  get "/aup",                   to: "static#aup",                 as: :aup
  get "/impressum",             to: "static#impressum",           as: :impressum

  # Only accessible on development
  if Rails.env.development?
    get "/base",                to: "static#base",              as: :base
  end

  get "/discover/(:filter)(/near/:near)(/category/:category)(/tags/:tags)(/search/:search)", to: "discover#index", as: :discover

  resources :tags, only: [:index]

  namespace :reports do
    resources :contribution_reports_for_project_owners, only: [:index]
  end

  # Temporary
  get '/projects/neuse-river-greenway-benches-draft', to: redirect('/projects/neuse-river-greenway-benches')

  resources :projects, except: [ :destroy ] do
    resources :faqs, controller: 'projects/faqs', only: [ :index, :create, :destroy ]
    resources :terms, controller: 'projects/terms', only: [ :index, :create, :destroy ]
    resources :updates, controller: 'projects/updates', only: [ :index, :create, :destroy ]

    collection do
      get 'video'
    end

    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'embed_panel'
      get 'comments'
      get 'reports'
      get 'budget'
      get 'success'
    end

    resources :rewards, only: [ :index, :create, :update, :destroy, :new, :edit ] do
      member do
        post 'sort'
      end
    end

    resources :contributions, controller: 'projects/contributions', except: :update do
      member do
        put 'credits_checkout'
      end
    end
  end

  resources :users, path: 'users' do
    resources :questions, controller: 'users/questions', only: [:new, :create]
    resources :projects, controller: 'users/projects', only: [ :index ]
    resources :contributions, controller: 'users/contributions', only: [:index] do
      member do
        get :request_refund
      end
    end

    resources :authorizations, controller: 'users/authorizations', only: [:destroy]
    resources :unsubscribes, only: [:create]
    member do
      get :settings
      get :credits
      get :payments
      get :edit
      put :update_email
      put :update_password
    end
  end

  namespace :companies do
    get :contact, to: 'contacts#new'
    resources :contacts, only: [:create]
  end

  # Redirect from old users url to the new
  #get "/users/:id", to: redirect('neighbors/%{id}')

  get "/set_email" => "users#set_email", as: :set_email_users
  get "/:id", to: redirect('projects/%{id}')
  mount CatarsePaypalExpress::Engine => "/", :as => "catarse_paypal_express"

end

app/models/reward.rb
# coding: utf-8
class Reward < ActiveRecord::Base
  include RankedModel

  belongs_to :project
  has_many :contributions

  ranks :row_order, with_same: :project_id

  validates_presence_of :title, :minimum_value, :description
  validates_numericality_of :minimum_value, greater_than_or_equal_to: 10.00
  validates_numericality_of :maximum_contributions, only_integer: true, greater_than: 0, allow_nil: true
  scope :remaining, -> { where("maximum_contributions IS NULL OR (maximum_contributions IS NOT NULL AND (SELECT COUNT(*) FROM contributions WHERE state IN ('confirmed', 'waiting_confirmation') AND reward_id = rewards.id) < maximum_contributions)") }
  scope :sort_asc, -> { order('id ASC') }
  scope :not_soon, -> { where('soon is not true') }
  scope :soon, -> { where(soon: true) }

  delegate :display_deliver_prevision, :display_remaining, :name, :display_minimum,
           :medium_description, :last_description, :display_description, to: :decorator
  def decorator
    @decorator ||= RewardDecorator.new(self)
  end

  def sold_out?
    maximum_contributions && total_compromised >= maximum_contributions
  end

  def total_compromised
    contributions.with_states(['confirmed', 'waiting_confirmation']).count
  end

  def remaining
    return nil unless maximum_contributions
    maximum_contributions - total_compromised
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  after_filter :verify_authorized, except: :index
  inherit_resources
  belongs_to :project, finder: :find_by_permalink!
  respond_to :html, :json

  def index
    render layout: !request.xhr?
  end

  def new
    @reward = Reward.new(project: parent)
    authorize @reward
    render layout: !request.xhr?
  end

  def edit
    authorize resource
    render layout: !request.xhr?
  end

  def update
    authorize resource
    update! { project_path(parent) }
  end

  def create
    @reward = Reward.new(permitted_params[:reward].merge(project: parent))
    authorize resource
    create! { project_path(parent) }
  end

  def destroy
    authorize resource
    destroy! { project_path(resource.project) }
  end

  def sort
    authorize resource
    resource.update_attribute :row_order_position, params[:reward][:row_order_position]

    render nothing: true
  end

  private
  def permitted_params
    params.permit(policy(@reward || Reward).permitted_attributes)
  end
end

app/views/rewards/_form.html.slim
= simple_form_for [parent, resource], html: { class: 'remote-form' } do |f|
  .pull-right
    a.cancel.button.secondary href="#" = t('words.cancel')
  .clearfix

  - if policy(resource).permitted_for?(:title, :update)
    = f.input :title

  - if policy(resource).permitted_for?(:minimum_value, :update)
    = f.input :minimum_value, as: :integer, input_html: {pattern: "^[\\d+.]+"}

  - if policy(resource).permitted_for?(:days_to_delivery, :update)
    = f.input :days_to_delivery

  - if policy(resource).permitted_for?(:description, :update)
    = f.input :description

  - if policy(resource).permitted_for?(:maximum_contributions, :update)
    = f.input :maximum_contributions

  = f.input :soon, as: :boolean

  = f.button :submit, data: { disable_with: t('words.sending') }
  - if resource.persisted? && policy(resource).destroy?
    span.or = t('words.or')
    = link_to [parent, resource], class: 'button alert', method: :delete, confirm: t('words.confirm') do
      i.icon-et-trash.icon-white
      = t('words.delete')

app/views/rewards/edit.html.slim
= render 'form'

app/views/rewards/index.html.slim
- collection.rank(:row_order).each do |reward|
  div[id="reward-#{reward.id}" data-update-path=sort_project_reward_path(parent, reward) data-new-project-contribution-path=new_project_contribution_path(parent, reward_id: reward.id) class="reward #{ 'clickable' if parent.online? && !reward.sold_out? && !reward.soon? } #{ 'sortable' if policy(reward).update? } #{ 'soon' if reward.soon? }"]
    header.title
      = t('.reward_title', minimum: reward.display_minimum).html_safe
      - if policy(reward).update?
        = link_to edit_project_reward_path(parent, reward), data: { element: ".edit-#{reward.id}-reward-form", path: edit_project_reward_path(parent, reward) }, class: 'edit' do
          i.icon-et-pencil

    div[class="edit-#{reward.id}-reward-form"]
      .loading.hide
        = image_tag 'loading.gif'
      .form-content.hide

    - if reward.maximum_contributions
      - if reward.sold_out?
        .sold-out
          .wrapper
            h4
              i.icon-et-cancel-squared
              br/
              = t('.sold_out')
      .maximum-contributions
        i.icon-et-alert
        = reward.display_remaining

        - in_time_to_confirm = reward.contributions.with_state('waiting_confirmation').count
        - if in_time_to_confirm > 0
          .pending = t('.contributions_to_confirm', count: in_time_to_confirm)

    .title = reward.title
    .description = reward.display_description

    - if reward.days_to_delivery.present?
      .days-to-delivery
        p = "#{t('.reward_deliver_time', prevision: reward.display_deliver_prevision)}".html_safe

- if policy(parent).update?

  .reward.new-reward-form
    .loading.hide
      = image_tag 'loading.gif'
    .form-content.hide

  .reward.add-reward
    = link_to new_project_reward_path(parent), data: { element: '.new-reward-form', path: new_project_reward_path(parent) } do
      i.icon-et-plus
      br/
      = t('.add')

app/views/rewards/new.html.slim
= render 'form'